ipfs/gateway-conformance

- tests/t0118_gateway_car_test.go
Let's skip the test until the implementation is fixed. We want the CI here to be able to tell us if the framework is doing alright.
> skip t0118_gateway_car_test.go for now

- tests/t0113_gateway_symlink_test.go
- tests/t0114_gateway_subdomains_test.go
- tests/t0117_gateway_block_test.go
- tests/t0118_gateway_car_test.go
- tooling/check/check.go
- tooling/test/sugar.go
- tooling/test/test.go
> fix: move every test to sugar API

- .github/workflows/docker.yml
- .github/workflows/release-docker.yml
- .github/workflows/release.yml
- CHANGELOG.md
This PR sets up CHANGELOG driven releases for this repo. This will take care of creating GitHub Releases and tags.
It also modifies the Docker release set up so that we create Docker images whenever we publish a release.
Most of the testing will happen post-merge when we try to do the release.
> ci: automate release process of gateway-conformance

- tests/t0116_gateway_cache_test.go
- tooling/test/config.go
- tooling/test/report.go
This PR adds sugar to the t0116 implementation and adds missing test case implementations as comments.
The missing test case implementation cannot be uncommented yet because:
- we do not have support for IPNS records in fixtures
- we do not have support for handling dependencies between test cases
> chore: ensure t0116 test implements all the test cases sharness does

- tests/t0118_gateway_car_test.go
- tooling/check/car.go
Fixes the panic `body must be string, []byte, or a regular check` when we use a Car check.
> fix: return pointer in car check to be compatible with rest of API

- tests/t0112_gateway_cors_test.go
- tooling/check/check.go
- tooling/test/sugar.go
- tooling/test/test.go
- Previous Header checks have been augmented with `IsUnique` which was implicit before
- Added Check for `Has(strings)`, which makes a set comparison
- Templated `CheckNot` to take any type of Check and return the negation
> feat: t0112 cors testing

- go.mod
- tests/t0114_gateway_subdomains_test.go
See the context in https://github.com/ipfs/boxo/pull/326.
> fix: remove body check for subdomain redirection

- tests/path_gateway_raw_test.go
- tests/trustless_gateway_raw_test.go
We should tick `t0117` from #3 after this PR.
- This tests were missing: https://github.com/ipfs/kubo/blob/master/test/sharness/t0117-gateway-block.sh#L32-L45
- We should really start removing sharness tests from Kubo to avoid doing this again: we updated the tests after they were ported.
- Removed Kubo specifics.
> feat: remove Kubo-specifics from RAW tests and add range tests

- CHANGELOG.md
- tests/trustless_gateway_car_test.go
- tooling/check/car.go
Closes #83.
I had to add a `IgnoreRoots` option because the way the current CAR checks work, we **always** have to say something about the roots if we do a `Exactly`. So now you can ignore CAR roots on Exactly. Nevertheless, the logic for `CheckIsCarFile.Check` is getting quite hairy.
> feat: explicitly not check CAR roots

- CHANGELOG.md
Closes https://github.com/ipfs/gateway-conformance/issues/80
After release:
> release: v0.2

- CHANGELOG.md
- Makefile
- cmd/gateway-conformance/main.go
- gc
- tooling/test/report.go
Changes include:
- making sure Makefile commands create reports in the `reports` directory which is properly gitignored
- extracting docker build out of `test-docker` command
- filtering out the go test output so that it only shows failures by defult
- adding verbose flag to the test command which makes sure we show ALL go test output
- enriching test command output with information about stage transitions
- ensuring output directories exist
- switching the order of expected/actual requests/responses in the report
> chore: retrieve UX improvements from IPFS Thing 2023 workshop setup

- Makefile
- README.md
> README: document usage

- .github/workflows/test-kubo-e2e.yml
- .github/workflows/test-tooling.yml
- tooling/tmpl/tmpl_test.go
> feat: improve testing

- Makefile
- README.md
See https://github.com/pl-strflt/gotest-json-to-junit-xml/blob/main/gotest-json-to-junit-xml
Note: I dropped the dependency on `test-kubo`, the workflow might be used even by those testing a different gateway,
(see @aschmahmann request in https://filecoinproject.slack.com/archives/C050BPMU4SV/p1688137864882569)
> fix: local workflow

- .github/workflows/release-fixtures.yml
- .github/workflows/test-prod-e2e.yml
- .github/workflows/update-badge.yml
- CHANGELOG.md
- README.md
- aggregate-into-table.js
- aggregate.js
- go.mod
- tooling/car/merge.go
Contributes to #104
Add tooling to run tests over multiple gateways & merge the outputs into a single dashboard. This is using a few arbitrary production gateways for now.
Example of output: https://github.com/singulargarden/gateway-conformance/actions/runs/5680836848
Example of markdown: https://github.com/laurentsenta/gateway-conformance/blob/main/README.md (it links to ipfs/gateway-conformance, hence the gray status for now)
- Implement a similar test for dev gateways (see https://github.com/ipfs/gateway-conformance/issues/104#issuecomment-1621944117)
- tweak the production gateways we want to test and the specs we cover
> feat: test production gateways

- tests/path_gateway_raw_test.go
The max-age is arbitrary, we the message here should match the test.
We use `29030400` everywhere, so changing to that.
> chore: fix test message

- .github/actions/extract-fixtures/action.yml
- .github/actions/test/action.yml
This is needed because of the upstream fixes we applied to GitHub action in docker container action. Action ref output now holds ref instead of a sha like before.
> fix: refs in extract fixtures and test

- tests/path_gateway_dag_test.go
- tests/path_gateway_unixfs_test.go
- tests/subdomain_gateway_ipfs_test.go
Closes #127. Adds some 404 tests as per the issue.
> feat: test 404 on UnixFS and DAG-JSON/CBOR paths

- tests/path_gateway_ipns_test.go
Closes #38.
This tests do not need fixtures. The redirects should happen without need for resolution.
> feat: test 302 /ipns/{legacy-peerid} → /ipns/{cidv1-libp2p-key-base36}

- .github/actions/extract-fixtures/action.yml
- .github/actions/test/action.yml
- .github/workflows/release-docker.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- aggregate-into-table.js
- aggregate.js
- cmd/gateway-conformance/main.go
- tests/metadata_test.go
- tooling/env.go
- tooling/metadata.go
We want to output the version as a piece of metadata during testing. We will use this metadata during dashboard generation to signal gateways using different versions of the conformance test suite.
Example output: note the **version** in the dashboard
https://github.com/ipfs/gateway-conformance/actions/runs/5761510674/attempts/1#summary-15619660151
Supports https://github.com/ipfs/gateway-conformance/issues/123
> [!NOTE]
> This PR introduces metadata output, which we'll reuse for other pieces of data. This allows us to add more details to our tests, like a gateway checker id, specs id, etc.
> For now, we're using a special log format `--- META: ...`. This is a **temporary** workaround for the lack of metadata, which is being worked on in …
> feat: add version flag

- tests/trustless_gateway_car_test.go
Closes #126.
- Adds test for non-existing paths as defined in #126.
- This test will fail against both Kubo master and Kubo latest until https://github.com/ipfs/kubo/pull/10024 is merged.
> feat: 404 test for trustless gateway CARs

- .github/workflows/test-implementations-e2e.yml
contributes to #123 
depends on https://github.com/ipfs/gateway-conformance/pull/145
example output: https://github.com/ipfs/gateway-conformance/actions/runs/5924237972/attempts/1#summary-16061404658
related:
- https://github.com/ipfs/bifrost-gateway/pull/195
- https://github.com/ipfs/kubo/pull/10092
- https://github.com/ipfs/boxo/pull/442
> feat: test implementations with reusable jsons

- .github/workflows/test-kubo-e2e.yml
setup-go@v4 comes with Go modules caching enabled by default.
> ci: remove obsolete protocol/cache-go-action

- CHANGELOG.md
- aggregate-into-table.js
- aggregate.js
- tests/dnslink_gateway_test.go
- tests/metadata_test.go
- tests/path_gateway_cors_test.go
- tests/path_gateway_dag_test.go
- tests/path_gateway_ipns_test.go
- tests/path_gateway_raw_test.go
- tests/path_gateway_tar_test.go
- tests/path_gateway_unixfs_test.go
- tests/redirects_file_test.go
- tests/subdomain_gateway_ipfs_test.go
- tests/subdomain_gateway_ipns_test.go
- tests/trustless_gateway_car_test.go
- tests/trustless_gateway_ipns_test.go
- tests/trustless_gateway_raw_test.go
- tooling/metadata.go
- tooling/test/sugar.go
- tooling/test/test.go
- tooling/test/validate.go
Contributes to #123 
Add a "User Taxonomy" different from the specs. This will be used in gateway checker and other user-facing tooling.
Add specs that connect with specs.ipfs.tech
⚠️ I'm not trying to assign specs and groups to all the tests for now, just demonstrate the specs API. We'll build the rest of the dashboard, maybe even a spec coverage table first.
Follow-ups:
> feat: add specs and user taxonomies

- munge_aggregates.js
- munge_sql.js
- tests/path_gateway_dag_test.go
- tests/path_gateway_tar_test.go
- tests/path_gateway_unixfs_test.go
- tests/redirects_file_test.go
- tests/trustless_gateway_car_test.go
- tests/trustless_gateway_raw_test.go
- www/content/_index.md
- www/content/specs/_index.md
- www/themes/conformance/assets/style.css
- www/themes/conformance/layouts/partials/breadcrumbs.html
- www/themes/conformance/layouts/partials/result-table.html
- www/themes/conformance/layouts/shortcodes/specs-links.html
- www/themes/conformance/layouts/specs/list.html
Contributes to https://github.com/ipfs/gateway-conformance/issues/123
Introduce specs dashboard side.
Example in https://singulargarden.github.io/gateway-conformance/specs/
We preserve the structure passed from specs.ipfs.tech to make linking and navigation easier.
For example:
https://singulargarden.github.io/gateway-conformance/specs/http-gateways/trustless-gateway/#entity-bytes-request-query-parameter
Note:
Tests are trees: `TestDagSomething/GET_Something/StatusCode`
And specs are also trees: `http-gateways/trustless-gateway/#entity-bytes-request-query-parameter`
What do you render for the spec `http-gateways/trustless-gateway`, especially if no tests are linking to that specific node in the tree?
The current PR renders all of its children, we'll have to refine this in further PRs.
> feat: with specs dashboard

- munge_aggregates.js
- tooling/test/test.go
- www/content/results/_index.md
- www/content/tests/_index.md
- www/themes/conformance/layouts/partials/head.html
Fixes the log rendering issue we've seen in bifrost
https://github.com/singulargarden/bifrost-gateway/actions/runs/6157325821/job/16707825616
Calling `t.Run("this is a test for /ipfs/something", ...)` will create outputs names like:
- `TestRoot/TestParent/this_is_a_test_for/ipfs/something/Body`
Which breaks the test generations and creates a _weird_ structure when rendering the tests.
Examples:
- https://singulargarden.github.io/gateway-conformance/results/bifrost-gateway/main/test-gateway-cache
- https://singulargarden.github.io/gateway-conformance/tests/test-gateway-cache/get-for-ipfs-with-only-if-cached-succeeds-when-in-local-datastore/status-code/
> fix: escape names that might collide with other operations

- CHANGELOG.md
- tests/path_gateway_dag_test.go
- tests/trustless_gateway_raw_test.go
- tooling/helpers/car.go
- tooling/helpers/range.go
- tooling/test/sugar.go
- tooling/test/test.go
- tooling/test/validate.go
- Add tests for #154 
- Adds basic `AnyOf` and `AllOf` helpers (related to #153)
- Range request helpers
- Added range requests tests for IPLD block requests
cc @laurentsenta @lidel
> feat: range request helpers

- tooling/helpers/range.go
> fix: byte range panic

- CHANGELOG.md
- tooling/helpers/range.go
note: this release contains new tests, which we'll mark as a breaking change,
see discussion in FIL Slack: 
https://filecoinproject.slack.com/archives/C04M8232QRW/p1695297349598999?thread_ts=1695291735.173199&cid=C04M8232QRW
> release: v0.4.0

- .github/workflows/test-kubo-e2e.yml
- CHANGELOG.md
- tests/path_gateway_dag_test.go
- tests/path_gateway_unixfs_test.go
This updates the conformance tests to bring them in line with the changes on the following PRs:
- https://github.com/ipfs/specs/pull/436
- https://github.com/ipfs/boxo/pull/459
- https://github.com/ipfs/kubo/pull/10115
Currently, we are not allowing `Cache-Control` headers in `/ipns` paths, but that's about to change.
> Tests for `/ipns` paths and `Cache-Control` HTTP header

- Makefile
Fixes the issue noted by @SgtPooki (#184) regarding `make provision-kubo`. It seems we forgot to update the Makefile to ignore everything after the `_` when we starting adding more information to the record filename.
> fix(make): correctly infer ipns name from record filename

- docs/commands.md
This PR aims to clarify some of the confusion from https://github.com/ipfs/gateway-conformance/issues/185
(There is no "simulating" per se, `Host` is just how cleartext HTTP works, every website on the internet  is routed to a proper handler this way)
Closes #185
> docs: clarify subdomain-url

- tests/trustless_gateway_car_test.go
Fix #189 
Insure `entity-bytes` negative index test properly verifies that the last block of the underlying file is not read.
> fix(tests): properly test negative indexing

- tests/path_gateway_dag_test.go
As per our conversation [here](https://github.com/ipfs/boxo/pull/587#pullrequestreview-1992168667), this removes the range test for `dag-cbor` objects that have been requested as `text/html`.
> feat: remove range test for dag-cbor as text/html

- README.md
```bash
> docker run -v "${PWD}:/workspace" -w "/workspace" ghcr.io/ipfs/gateway-conformance:v0.4.2 extract-fixtures --output fixtures --merged false
Status: Downloaded newer image for ghcr.io/ipfs/gateway-conformance:v0.4.2
Incorrect Usage: flag provided but not defined: -output
NAME:
gateway-conformance extract-fixtures - Extract gateway testing fixtures that are used by the conformance test suite
USAGE:
gateway-conformance extract-fixtures command [command options] [arguments...]
COMMANDS:
help, h  Shows a list of commands or help for one command
OPTIONS:
--directory value, --dir value  The directory to extract the fixtures to
--merged                        Merge the fixtures into a single CAR file (default: false)
--help, -h                      show help
2023/12/04 20:54:15 flag …
```
> docs(readme): docker extract-fixtures --s/output/directory/

- README.md
Fixes https://github.com/ipfs/gateway-conformance/issues/184
> docs: add install instructions for cli use

- tooling/check/check_has_test.go
- tooling/test/header_test.go
- tooling/test/sugar.go
Initial commit shows the problem mentioned in https://github.com/ipfs/gateway-conformance/issues/186
later commits fix the failing test
fixes https://github.com/ipfs/gateway-conformance/issues/186
contributes to #21
> fix: Header().Has works properly for checking multiple values

- CHANGELOG.md
- tests/path_gateway_unixfs_test.go
Applies https://github.com/ipfs/gateway-conformance/pull/218 in a backward-compatible way, allowing us to ship as a patch release while we finalize the specs.
> fix: Cache-Control for generated UnixFS dir listings on /ipfs

- CHANGELOG.md
- tests/path_gateway_tar_test.go
The error message in boxo was [fixed](https://github.com/ipfs/boxo/pull/653/files#diff-1f636927091be5710efa23d3ac59429fe81b9ddcc290ce4e6b276539a665f167L13-R13) to say "not allowed" instead of "now allowed". The message that the gateway conformance test looks for needs to match.
> fix(tar): test status and not body

- .github/workflows/deploy-pages.yml
the website was deprioritizedpost nucleation,
switching to on-demand build for now
> chore(ci): disable unused workflows

- CHANGELOG.md
- tests/path_gateway_dag_test.go
Fixes https://github.com/ipfs/gateway-conformance/issues/240
> fix: dag-index html cache-control matches dir-index html

- CHANGELOG.md
- tests/trustless_gateway_car_test.go
- tooling/helpers/car.go
The response code for non-existing paths now depends on implementation details such as locality and cost of path traversal checks.
- Implementations that can efficiently detect non-existing paths before returning HTTP headers should return 404 Not Found (improved behavior per https://github.com/ipfs/boxo/issues/458)
- Implementations focusing on stateless streaming and low latency may return 200 with partial CAR up to the missing link (legacy behavior)
This change:
- Updates TestTrustlessCarPathing to use AnyOf for non-existing file test
- Enhances applyStandardCarResponseHeaders to handle AnyOfExpectBuilder
- Applies CAR headers only to 200 responses, not to 404 error responses
> feat: relax CAR tests to accept both 200 and 404 for non-existing paths
